bboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from collections import namedtuple
from django.urls import path
from .views import RegisterUserView, index, other_page, BBLoginView, profile, BBLogoutView, ChangeUserInfoView,BBPasswordChangeView
from .views import RegisterUserView, RegisterDoneView, user_activate, DeleteUserView
from .views import by_rubric
from .views import detail


app_name = 'main'

urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('acconts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('acconts/profile/change', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<str:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.fields import BLANK_CHOICE_DASH
from .utilities import get_timestamp_path

class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True,
    verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True, verbose_name='Присылать оповещения о новых комментариях?')

    def delete(self, *args, **kwargs):
        for bb in self.bb_set.all():
            bb.delete()
        super().delete(*args, **kwargs)
        
    class Meta(AbstractUser.Meta):
        pass

class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, unique=True, verbose_name='Название')
    order = models.SmallIntegerField(default=0, db_index=True, verbose_name='Порядок')
    super_rubric = models.ForeignKey('SuperRubric', on_delete=models.PROTECT, null=True, blank=True, verbose_name='Надрубрика')


class SuperRubricManager(models.Manager):
    def get_queryset(self):
       return super().get_queryset().filter(super_rubric_id=True)

class SuperRubric(Rubric):
    objects = SuperRubricManager()
    def __str__(self):
        return self.name

    class Meta:
        proxy = True
        ordering = ('order', 'name')
        verbose_name = 'Надрубрика'
        verbose_name_plural = 'Надрубрики'


class SubRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric_id=False)

class SubRubric(Rubric):
    objects = SubRubricManager()

    def __str__(self):
        return (self.super_rubric.name, self.name)

    class Meta:
        proxy = True
        ordering = ('order', 'name')
        verbose_name = 'Подрубрика'
        verbose_name_plural = 'Подрубрики'


class Bb(models.Model):
    rubric = models.ForeignKey(SubRubric, on_delete=models.PROTECT, verbose_name='Рубрика')
    title = models.TextField(max_length=40, verbose_name='Товар')
    content = models.TextField(verbose_name='Описание')
    price = models.FloatField(default=0, verbose_name='Цена')
    contacts = models.TextField(verbose_name='Контакты')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Изображения')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE, verbose_name='Автор обьявления')
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='Выводить в списке?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')

    def delete(self, *args, **kwargs):
        for ai in self.additionalimage_set.all():
            ai.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Обьявления'
        verbose_name = 'Обьявления'
        ordering = ['-created_at']


class AdditionalImage(models.Model):
    bb = models.ForeignKey(Bb, on_delete=models.CASCADE, verbose_name='Обьявления')
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name='Изображение')

    class Meta:
        verbose_name_plural = 'Дополнительные изображения'
        verbose_name = 'Дополнительное изображение'

main/forms.py
#from .admin import SuperRubricAdmin
from django import forms
from django.forms import fields
from .models import AdvUser
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .apps import user_registreted
from .models import SuperRubric, SubRubric

class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(
        queryset=SuperRubric.objects.all(), empty_label=None, label='Надрубрика', required=True)
    class Meta:
        model = SubRubric
        fields = '__all__'

class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
    help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль(повторно)',
    widget=forms.PasswordInput,
    help_text='Введите тот же самый пароль для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch'
            )}
            raise ValidationError(errors)
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registreted.send(RegisterUserForm, instance=user)
        return user
    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages')

class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес вашей электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='')

main/views.py
from django.db import models
from django.forms.fields import RegexField
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404 
from .models import AdvUser
from .forms import ChangeUserInfoForm, RegisterUserForm
from django.views.generic.base import TemplateView
from django.core.signing import BadSignature
from .utilities import signer
from django.contrib.auth import logout
from django.contrib import messages
from django.core.paginator import PageNotAnInteger, Paginator
from django.db.models import Q 
from .models import SubRubric, Bb
from .forms import SearchForm

def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'rubric': rubric, 'page': page, 'bbs': page.object_list,
    'form': form}
    return render(request, 'main/by_rubric.html', context)

class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/delete_user.html'
    success_url = reverse_lazy('main:index')
    
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk 
        return super().setup(request, *args, **kwargs)
    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)



def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'main/user_is_activated.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)

class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'

class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')

class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль успешно изменен'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk 
        return super().setup(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)
            

class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'

@login_required
def profile(request):
    return render(request, 'main/profile.html')

class BBLoginView(LoginView):
    template_name = 'main/login.html'

def other_page(request, page):
    try:
        template = get_template('main/'+ page +'.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

def index(request):
    return render(request, 'main/index.html')

def detail(request, rubric_pk, pk):
    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalImage_set.all()
    context = {'bb': bb, 'ais': ais}
    return render(request, 'main/detail.html', context)

main/templates/main/about.html
{% extends 'layout/base.html' %}

{% block title %}
    О сайте
{% endblock title %}

{% block content %}
    <h2>О сайте</h2>
    <p>Сайт для публикации обьявлений</p>
    <p>Все права на публикации принадлежат их авторам</p>
    <p><h6>При создании сайта использованы рекомендации книни Django3.0 Дронова</h6></p>
{% endblock content %}
    
    

main/templates/main/activation_done.html
{% extends 'layout/base.html' %}

{% block title %}
    Активация выполнена
{% endblock title %}

{% block content %}
    <h2>Активация</h2>
    <p>Пользователь с таким именем успешно активирован</p>
    <p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock content %}
    

main/templates/main/bad_signature.html
{% extends 'layout/base.html' %}

{% block title %}
    Ошибка активации
{% endblock title %}

{% block content %}
    <h2>Активация</h2>
    <p>Активация пользователя с таким именем прошла неудачно</p>
    <p><a href="{% url 'main:register' %}">Зарегистрироваться еще раз</a></p>
{% endblock content %}
    
    

main/templates/main/by_rubric.html
{% extends 'layout/base.html' %}
{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}


{% block title %}
    {{ rubric }}
{% endblock title %}

{% block content %}
    <h1 class="mb-2">{{ rubric }}</h1>
    <div class="container-fluid mb-2">
        <div class="row">
            <div class="col">&nbsp;</div>
            <form action="" class="col-md-auto form-inline">
                {% bootstrap_form form show_label=False %} 
                {% bootstrap_button content='Искать' button_type='submit' %} 
            </form>
        </div>
    </div>
    { if bbs %} 
        <ul class="list-unstyled">
            {% for bb in bbs %} 
                <li class="media my-5 p-3 border">
                    {% url 'main:detail' rubric_pk=rubric.pk pk=bb.pk as url %} 
                    <a href="{{ url }}{{ all }}">
                        {% if bb.image %} 
                            <img src="{% thimbnail bb.image 'default' %}" alt="image" class="mr-3">
                        {% else %} 
                            <img src="{% static 'main/empty.jpg' %}" alt="empty" class="mr-3">
                        {% endif %} 
                    </a>
                    <div class="media-body">
                        <h3>
                            <a href="{{ url }}{{ all }}">
                                {{ bb.title }}
                            </a>
                        </h3>
                        <div>{{ bb.content }}</div>
                        <p class="tezt-right forn-weight-bold">{{ bb.price }} руб.</p>
                        <p class="text-right forn-italic">{{ bb.crated_at }}</p>
                    </div>
                </li>
            {% endfor %} 
        </ul>
        {% bootstrap_pagination page url=keyword %} 
    {% endif %} 
{% endblock content %}
    
    

main/templates/main/change_user_info.html
{% extends 'layout/base.html' %}
{% load bootstrap4 %}
{% block title %}
    Изменение личных данных пользователя
{% endblock title %}
{% block content %}
    <h2> Изменение личных данных пользователя {{ user.username }}</h2>
        <form action="" method="POST">
        {% csrf_token %} 
        {% bootstrap_form form layout='horizontal' %} 
        {% buttons submit='Сохранить изменения' %}{% endbuttons %}
        </form>
{% endblock content %}
    
    

main/templates/main/delete_user.html
{% extends 'layout/base.html' %}
{% load bootstrap4 %}

{% block title %}
    Удаление пользователя
{% endblock title %}

{% block content %}
    <h2>Удаление пользователя {{ object.username }}</h2>
    <form action="" method="post">
        {% csrf_token %}
        {% buttons submit='Удалить' %}{% endbuttons %}
    </form>
{% endblock content %}
    
    

main/templates/main/detail.html
{% extends 'layout/base.html' %}

{% block title %}
    {{ bb.title }} - {{ bb.rubric.name }}
{% endblock title %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row">
            {% if bb.image %} 
                <div class="col-md-auto">
                    <img src="{{ bb.image.url }}" alt="" class="main-image">
                </div>
            {% endif %} 
            <div class="col">
                <h2>{{ bb.title }}</h2>
                <p>{{ bb.content }}</p>
                <p class="font-weight-bold">{{ bb.price }} руб.</p>
                <p>{{ bb.contacts }}</p>
                <p class="text-right font-italic">Добавлено {{ bb.created_at }}</p>
            </div>
        </div>
    </div>
    {% if ais %} 
    <div class="d-flex justify-content-between flex-wrap mt-5">
        {% for ai in ais %} 
            <div>
                <img src="{{ ai.image.url }}" alt="" class="additional-image">
            </div>
        {% endfor %} 
    </div>
    {% endif %} 
    <p><a href="{% url 'main:by_rubric' pk=bb.rubric.pk %}{{ all }}">Назад</a></p>
{% endblock content %}
    
    

main/templates/main/index.html
{% extends 'layout/base.html' %}

{% block content %}
    <h2>Последние 10 обьявлений</h2>
{% endblock content %}
    

main/templates/main/login.html
{% extends 'layout/base.html' %}
{% load bootstrap4 %}
{% block title %}
    Вход
{% endblock title %}

{% block content %}
    <h2>Вход на сайт</h2>
    
    {% if user.is_authenticated %}
        <p>Вы уже вошли</p>
    {% else %}
        <form action="" method="POST">
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %} 
            <input type="hidden" name="next" value="{{ next }}">
            {% buttons submit='Войти' %} {% endbuttons %} 
        </form>
        
    {% endif %}
        
{% endblock content %}
    
    

main/templates/main/logout.html
{% extends 'layout/base.html' %}

{% block title %}
    Выход
{% endblock title %}

{% block content %}
    <h2>Выход</h2>
    <p>вы успешно вышли с сайта</p>
{% endblock content %}
    
    

main/templates/main/profile.html
{% extends 'layout/base.html' %}

{% block title %}
    Профиль пользователя
{% endblock title %}

{% block  content %}
    <h2>Профиль пользователя {{ user.username }}</h2>
    
    {% if user.first_name and user.last_name %}
        <p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
    {% else %}
        <p>Здравствуйте</p>
    {% endif %}
    <h3>Ваши обьявления</h3>
        
{% endblock %}
    
    

main/templates/main/register_done.html
{% extends 'layout/base.html' %} 

{% block title %}
     Регистрация успешно завершена
{% endblock title %}

{% block content %}
    <h2>Регистрация</h2>
    <p>Регистрация успешно завершена</p>
    <p>На адрес электронной почты, указанный пользователем, отправлено сообщение активации</p>
{% endblock content %}
    
    

main/templates/main/register_user.html
{% extends 'layout/base.html' %}
{% load bootstrap4 %} 

{% block title %}
    Регистрация
{% endblock title %}

{% block content %}
    <h2>Регистрация нового пользователя</h2>
    <form method="POST">
        {% csrf_token %} 
        {% bootstrap_form form layout='horizontal' %} 
        {% buttons submit='Зарегистрироваться' %}{% endbuttons %} 
    </form>
{% endblock content %}
    
    

main/templates/main/user_is_activated.html
{% extends 'layout/base.html' %}

{% block title %}
    Пользователь активирован ранее
{% endblock title %}

{% block content %}
    <h2> Активация</h2>
    <p>Пользователь с таким именем активирован ранее</p>
    <p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock content %}
    